name: fala_doutor_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  drift: ^2.15.0
  postgres: ^2.6.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  build_runner: ^2.4.8
  drift_dev: ^2.15.0