name: fala_doutor_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^2.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6