name: fala_doutor_api
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  drift: ^2.18.0
  drift_postgres: ^1.2.0
  postgres: ^3.0.6
  path: ^1.9.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

  build_runner: ^2.4.8
  drift_dev: ^2.18.0